const express = require('express');
const cors = require('cors');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const axios = require('axios');
const FormData = require('form-data');
const localtunnel = require('localtunnel');

const app = express();
app.use(cors());
// Increase limits for receiving base64 images
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ extended: true, limit: '50mb' }));

// ─── Dynamic Tunnel Config ───
let tunnelUrl = null; // Set via the config page
let myWebhookUrl = null; // Generated by our own localtunnel

// ─── Generation State ───
// Tracks the current status for the frontend to poll
let generationState = { status: 'idle', imageUrl: null, error: null };

// Ensure uploads directory exists and is empty on startup
const UPLOADS_DIR = path.join(__dirname, 'uploads');
if (!fs.existsSync(UPLOADS_DIR)) {
  fs.mkdirSync(UPLOADS_DIR);
} else {
  // Empty the folder on every launch to save space
  const files = fs.readdirSync(UPLOADS_DIR);
  for (const file of files) {
    fs.unlinkSync(path.join(UPLOADS_DIR, file));
  }
  console.log(`🧹 Cleaned up ${files.length} old temporary images from uploads folder.`);
}

// ─── Config Page (opens first in browser) ───
app.get('/config', (req, res) => {
  res.send(`
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ImagiFit — Connect to AI Server</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Inter', sans-serif;
      background: linear-gradient(135deg, #0f0c29, #302b63, #24243e);
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      color: #fff;
    }
    .card {
      background: rgba(255,255,255,0.06);
      backdrop-filter: blur(20px);
      border: 1px solid rgba(255,255,255,0.1);
      border-radius: 20px;
      padding: 40px;
      width: 520px;
      max-width: 90vw;
      box-shadow: 0 25px 60px rgba(0,0,0,0.4);
    }
    .card h1 {
      font-size: 24px;
      font-weight: 700;
      margin-bottom: 6px;
      background: linear-gradient(135deg, #a78bfa, #60a5fa);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
    }
    .card p.subtitle {
      font-size: 14px;
      color: rgba(255,255,255,0.5);
      margin-bottom: 28px;
    }
    label {
      display: block;
      font-size: 13px;
      font-weight: 500;
      color: rgba(255,255,255,0.7);
      margin-bottom: 8px;
    }
    textarea {
      width: 100%;
      height: 120px;
      background: rgba(255,255,255,0.08);
      border: 1px solid rgba(255,255,255,0.15);
      border-radius: 12px;
      color: #fff;
      font-family: 'SF Mono', 'Fira Code', monospace;
      font-size: 13px;
      padding: 14px;
      resize: none;
      outline: none;
      transition: border-color 0.2s;
    }
    textarea:focus {
      border-color: #a78bfa;
    }
    textarea::placeholder {
      color: rgba(255,255,255,0.25);
    }
    .hint {
      font-size: 11px;
      color: rgba(255,255,255,0.35);
      margin-top: 8px;
      margin-bottom: 24px;
    }
    button {
      width: 100%;
      padding: 14px;
      background: linear-gradient(135deg, #a78bfa, #60a5fa);
      border: none;
      border-radius: 12px;
      color: #fff;
      font-family: 'Inter', sans-serif;
      font-size: 15px;
      font-weight: 600;
      cursor: pointer;
      transition: transform 0.15s, box-shadow 0.15s;
    }
    button:hover {
      transform: translateY(-2px);
      box-shadow: 0 8px 25px rgba(167,139,250,0.4);
    }
    button:active { transform: translateY(0); }
    button:disabled {
      opacity: 0.5;
      cursor: not-allowed;
      transform: none;
      box-shadow: none;
    }
    .status {
      margin-top: 16px;
      text-align: center;
      font-size: 13px;
      min-height: 20px;
    }
    .status.error { color: #f87171; }
    .status.success { color: #34d399; }
    .icon { font-size: 40px; text-align: center; margin-bottom: 16px; }
  </style>
</head>
<body>
  <div class="card">
    <div class="icon">🔗</div>
    <h1>Connect to AI Server</h1>
    <p class="subtitle">Paste your friend's tunnel info below to connect</p>
    
    <label for="tunnelInfo">Tunnel Info</label>
    <textarea id="tunnelInfo" placeholder="🌐 Public Tunnel URL: https://example.loca.lt
⚙️  API Endpoint:     https://example.loca.lt/process
🔑 Password/IP:       123.456.789.0"></textarea>
    <div class="hint">Paste the full block your friend gives you. The URL will be auto-extracted.</div>

    <button id="connectBtn" onclick="connect()">🚀 Connect & Launch App</button>
    <div class="status" id="status"></div>
  </div>

  <script>
    async function connect() {
      const btn = document.getElementById('connectBtn');
      const status = document.getElementById('status');
      const raw = document.getElementById('tunnelInfo').value.trim();

      if (!raw) {
        status.className = 'status error';
        status.textContent = 'Please paste the tunnel info first!';
        return;
      }

      // Extract the tunnel URL (look for https://...loca.lt pattern)
      const urlMatch = raw.match(/https:\\/\\/[\\w.-]+\\.loca\\.lt/);
      if (!urlMatch) {
        status.className = 'status error';
        status.textContent = 'Could not find a .loca.lt URL in the pasted text!';
        return;
      }

      const tunnelUrl = urlMatch[0];
      btn.disabled = true;
      btn.textContent = '⏳ Connecting...';
      status.className = 'status';
      status.textContent = 'Saving tunnel URL: ' + tunnelUrl;

      try {
        const res = await fetch('/api/set-tunnel', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ tunnelUrl })
        });
        const data = await res.json();

        if (data.success) {
          status.className = 'status success';
          status.textContent = '✅ Connected! Launching app...';
          setTimeout(() => {
            window.location.href = 'http://localhost:5173';
          }, 800);
        } else {
          throw new Error(data.error || 'Unknown error');
        }
      } catch (err) {
        status.className = 'status error';
        status.textContent = '❌ ' + err.message;
        btn.disabled = false;
        btn.textContent = '🚀 Connect & Launch App';
      }
    }
  </script>
</body>
</html>
  `);
});

// ─── API: Set Tunnel URL & Send Handshake ───
app.post('/api/set-tunnel', async (req, res) => {
  const { tunnelUrl: url } = req.body;
  if (!url) {
    return res.status(400).json({ success: false, error: 'No tunnel URL provided' });
  }
  tunnelUrl = url.replace(/\/$/, ''); // Remove trailing slash
  console.log(`\n✅ Tunnel URL configured: ${tunnelUrl}`);
  console.log(`   API Endpoint: ${tunnelUrl}/process`);
  
  if (!myWebhookUrl) {
    console.warn(`⚠️ Warning: My localtunnel isn't ready yet, registration handshake may fail.`);
  } else {
    try {
      console.log(`🤝 Sending registration handshake to AI Server...`);
      await axios.post(`${tunnelUrl}/register`, {
        client_webhook_url: `${myWebhookUrl}/webhook`
      }, {
        headers: {
          'Bypass-Tunnel-Reminder': 'true'
        }
      });
      console.log(`✅ Handshake successful! AI server knows our webhook.`);
    } catch (err) {
      console.error(`⚠️ Registration handshake failed:`, err.response?.data || err.message);
      // We don't fail the frontend request if handshake fails, just log it.
    }
  }

  res.json({ success: true, tunnelUrl });
});

// ─── API: Check if tunnel is configured ───
app.get('/api/tunnel-status', (req, res) => {
  res.json({ configured: !!tunnelUrl, tunnelUrl });
});

// Configure Multer for file uploads
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, UPLOADS_DIR);
  },
  filename: (req, file, cb) => {
    // Generate a random name for the client photo
    const randomHex = crypto.randomBytes(8).toString('hex');
    const ext = path.extname(file.originalname);
    cb(null, `client_${randomHex}${ext}`);
  }
});
const upload = multer({ storage });

// ─── API: Generate Image (Trigger Job) ───
app.post('/api/generate', upload.single('clientImage'), async (req, res) => {
  try {
    if (!tunnelUrl) {
      return res.status(400).json({ 
        success: false, 
        error: 'AI server not configured! Go to http://localhost:3001/config first.' 
      });
    }

    if (!req.file) {
      return res.status(400).json({ error: 'No client image uploaded' });
    }

    const clientImageName = req.file.filename;
    const clientImagePath = req.file.path;
    const clothingItemId = req.body.clothingId || 'unknown'; 

    const friendLaptopUrl = `${tunnelUrl}/process`;

    console.log(`[NETWORK EVENT] Received Generate Request`);
    console.log(`1. Client Image saved as: ${clientImageName}`);
    console.log(`2. Target Clothing ID: ${clothingItemId}`);
    console.log(`[NETWORK EVENT] Transmitting job to AI Server...`);

    // Prepare the form data to send to the friend's laptop
    const fileBuffer = fs.readFileSync(clientImagePath);
    const formData = new FormData();
    formData.append('clientImage', fileBuffer, { 
      filename: clientImageName,
      contentType: 'image/jpeg'
    });
    
    // Grab the corresponding clothing picture from the frontend assets
    const filenameMap = {
      '1': '001.jpeg',
      '2': '002.png',
      '3': '003.png',
      '4': '004.png'
    };
    const clothingFileName = filenameMap[clothingItemId] || '001.jpeg';
    const clothingImagePath = path.join(__dirname, '../frontend/src/assets', clothingFileName);
    
    if (fs.existsSync(clothingImagePath)) {
      const clothingBuffer = fs.readFileSync(clothingImagePath);
      formData.append('clothingImage', clothingBuffer, {
        filename: clothingFileName,
        contentType: clothingFileName.endsWith('.png') ? 'image/png' : 'image/jpeg'
      });
    }

    formData.append('clothingId', clothingItemId);

    // Reset the global state to processing
    generationState = { status: 'processing', imageUrl: null, error: null };

    try {
      // Send the POST request to the friend's laptop via Localtunnel
      const aiResponse = await axios.post(friendLaptopUrl, formData, {
        headers: {
          ...formData.getHeaders(),
          'Content-Length': formData.getLengthSync(),
          'Bypass-Tunnel-Reminder': 'true'
        },
        proxy: false
      });

      console.log(`[NETWORK EVENT] AI Server acknowledged job! Status:`, aiResponse.data);
      
      res.json({
        success: true,
        message: 'Job started successfully. Polling for results...',
      });

    } catch (networkError) {
      const serverFeedback = networkError.response?.data || networkError.message;
      console.error(`[NETWORK ERROR] AI Server rejected request:`, serverFeedback);
      generationState = { status: 'error', imageUrl: null, error: serverFeedback };
      
      res.json({
        success: false,
        error: 'The AI server rejected the request.',
        details: serverFeedback
      });
    }

  } catch (error) {
    console.error('Server error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// ─── API: Webhook Receiver (From AI Server) ───
app.post('/webhook', (req, res) => {
  console.log(`[WEBHOOK EVENT] Received payload from AI Server!`);
  
  // 1. Respond instantly so the tunnel doesn't time out
  res.status(200).json({ success: true });

  // 2. Process the image asynchronously in the background
  setTimeout(() => {
    try {
      const error = req.body.error;
      const generatedImageUrl = req.body.generatedImageUrl;
      
      if (error) {
        console.error(`[WEBHOOK EVENT] AI Server reported an error:`, error);
        generationState = { status: 'error', imageUrl: null, error };
        return;
      }

      if (!generatedImageUrl) {
        console.error(`[WEBHOOK EVENT] No image URL found in webhook payload.`);
        generationState = { status: 'error', imageUrl: null, error: 'Missing image URL' };
        return;
      }

      console.log(`[WEBHOOK EVENT] Received image URL: ${generatedImageUrl}`);
      
      // Update global state so frontend polling picks it up
      // We route the image through our proxy to inject the Bypass-Tunnel-Reminder header
      const proxyUrl = `http://localhost:3001/api/proxy-image?url=${encodeURIComponent(generatedImageUrl)}`;
      generationState = { 
        status: 'completed', 
        imageUrl: proxyUrl,
        error: null 
      };
    } catch (err) {
      console.error(`[WEBHOOK EVENT] Error processing webhook:`, err);
      generationState = { status: 'error', imageUrl: null, error: 'Failed to process webhook image' };
    }
  }, 0);
});

// ─── API: Image Proxy ───
app.get('/api/proxy-image', async (req, res) => {
  const targetUrl = req.query.url;
  if (!targetUrl) {
    return res.status(400).send('No URL provided');
  }

  try {
    const response = await axios({
      method: 'GET',
      url: targetUrl,
      responseType: 'stream',
      headers: {
        'Bypass-Tunnel-Reminder': 'true'
      }
    });

    res.setHeader('Content-Type', response.headers['content-type'] || 'image/jpeg');
    response.data.pipe(res);
  } catch (error) {
    console.error(`[PROXY ERROR] Failed to fetch image from ${targetUrl}:`, error.message);
    res.status(500).send('Error proxying image');
  }
});

// ─── API: Status Polling ───
app.get('/api/status', (req, res) => {
  res.json(generationState);
});

// Serve the uploads directory statically so the frontend can view the generated images
app.use('/uploads', express.static(UPLOADS_DIR));

const PORT = 3001;
let currentTunnel = null;

async function startTunnel() {
  try {
    if (currentTunnel) {
      currentTunnel.removeAllListeners(); // Prevent duplicate setTimeout loops
      currentTunnel.close();
    }
    
    currentTunnel = await localtunnel({ port: PORT, local_host: '127.0.0.1' });
    myWebhookUrl = currentTunnel.url;
    console.log(`📡 Mac's Webhook URL established at: ${myWebhookUrl}`);
    console.log(`🔗 Open http://127.0.0.1:${PORT}/config to connect to AI server\n`);
    
    // If the frontend has already set the friend's tunnel URL, instantly re-register!
    if (tunnelUrl) {
      console.log(`🔄 Tunnel reconnected! Re-registering handshake with AI Server...`);
      try {
        await axios.post(`${tunnelUrl}/register`, {
          client_webhook_url: `${myWebhookUrl}/webhook`
        }, { headers: { 'Bypass-Tunnel-Reminder': 'true' } });
        console.log(`✅ Re-registration successful!`);
      } catch (err) {
        console.error(`⚠️ Re-registration handshake failed:`, err.message);
      }
    }

    currentTunnel.on('close', () => {
      console.log('⚠️ Tunnel closed! Attempting to reconnect in 3 seconds...');
      setTimeout(startTunnel, 3000);
    });

    currentTunnel.on('error', (err) => {
      console.error('⚠️ Tunnel error:', err);
      currentTunnel.close(); // Triggers the 'close' event to restart it
    });

  } catch (err) {
    console.error('Failed to create localtunnel, retrying in 3 seconds...', err);
    setTimeout(startTunnel, 3000);
  }
}

app.listen(PORT, '127.0.0.1', () => {
  console.log(`\n🚀 Backend Hub running on http://127.0.0.1:${PORT}`);
  startTunnel();
});
